nlp_engine_name: spacy
models:
- lang_code: it
  model_name: it_core_news_sm
ner_model_configuration:
  model_to_presidio_entity_mapping:
    PER: PERSON
    LOC: LOCATION
    GPE: LOCATION
    ORG: ORGANIZATION
    DATE: DATE_TIME
    TIME: DATE_TIME
  labels_to_ignore:
  - CARDINAL
  - EVENT
  - LANGUAGE
  - LAW
  - MONEY
  - ORDINAL
  - PERCENT
  - PRODUCT
  - QUANTITY
  - WORK_OF_ART
  low_confidence_score_multiplier: 0.4
  low_score_entity_names:
  - ID
  - ORG
